HealthCatalyst/Fabric.Identity

Fabric.Identity.API/Authorization/ReadAuthorizationHandler.cs
Fabric.Identity.API/Authorization/ReadScopeRequirement.cs
Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Models/ModelExtensions.cs
Fabric.Identity.API/Models/UserApiModel.cs
Fabric.Identity.API/Services/AuditingDocumentDbService.cs
Fabric.Identity.API/Services/CouchDbAccessService.cs
Fabric.Identity.API/Services/IDocumentDbService.cs
Fabric.Identity.API/Services/InMemoryDocumentService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.UnitTests/ReadAuthorizationHandlerTests.cs

tests coming, this is all the supporting code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/33)

additions to support finding users by subject ids while filtering last login by clientid`

---

Fabric.Identity.API/Management/UsersController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/36)

added supporting code to generate swagger docs

---

Fabric.Identity.API/DocumentDbStores/DocumentDbUserStore.cs
Fabric.Identity.API/Services/AuditingDocumentDbService.cs
Fabric.Identity.API/Services/CouchDbAccessService.cs
Fabric.Identity.API/Services/IDocumentDbService.cs
Fabric.Identity.API/Services/InMemoryDocumentService.cs
Fabric.Identity.IntegrationTests/UsersStoreTests.cs
Fabric.Identity.UnitTests/UserStoreTests.cs

another minor change was the parameter name for the GetDocuments method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/39)

updated couchdb service to replace backslash with two colons for use in the document id

---

Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Models/UserSearchParameter.cs
Fabric.Identity.IntegrationTests/UsersStoreTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/40)

change users api parameter name to userIds

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

Also removed some functions that were moved to the common installation module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/42)

document installation config

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/setup-samples.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/43)

added steps to register Fabric.Authorization as a client in Fabric.Identity

---

Fabric.Identity.API/Management/UserLoginManager.cs
Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.UnitTests/UserLoginManagerTests.cs

i was also able to simplify the logic in the UserLoginManager so we only have a single code path now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/44)

ensure users are added to document store when logging in using internal or external flow

---

Fabric.Identity.API/scripts/setup-samples.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/45)

Set environment variables for installer and auth client secret 

---

Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Models/ExternalUser.cs
Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Quickstart/Account/AccountOptions.cs
Fabric.Identity.API/Services/ExternalIdentityProviderServiceResolver.cs
Fabric.Identity.API/Services/IExternalIdentityProviderServiceResolver.cs
Fabric.Identity.API/Services/LdapProviderService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.IntegrationTests/IntegrationTestsFixture.cs
Fabric.Identity.IntegrationTests/LdapProviderServiceTests.cs
Fabric.Identity.IntegrationTests/LdapTestHelper.cs
Fabric.Identity.IntegrationTests/UsersStoreTests.cs
Fabric.Identity.UnitTests/UserLoginManagerTests.cs

Added the user search API and created a resolver to resolve the appropriate IExternalIdentityProviderService at run time based on the search request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/47)

Added user search API

---

Fabric.Identity.API/Documentation/ParamMetadataOperationFilter.cs
Fabric.Identity.API/Documentation/TagFilter.cs
Fabric.Identity.API/Documentation/VersionRemovalOperationFilter.cs
Fabric.Identity.API/Extensions/ServiceCollectionExtensions.cs
Fabric.Identity.API/Management/IdentityProvidersController.cs
Fabric.Identity.API/Models/ExternalProvider.cs
Fabric.Identity.API/Models/ExternalProviderApiModel.cs
Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Quickstart/Account/AccountService.cs
Fabric.Identity.API/Quickstart/Account/LoginViewModel.cs
Fabric.Identity.API/Services/IIdentityProviderConfigurationService.cs
Fabric.Identity.API/Services/IdentityProviderConfigurationService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.API/Validation/ExternalProviderApiModelValidator.cs
Fabric.Identity.IntegrationTests/IdentityProvidersControllerTests.cs
Fabric.Identity.IntegrationTests/appsettings.json
Fabric.Identity.UnitTests/IdentityProviderConfigurationServiceTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/48)

Added endpoint for getting configured identity providers.

---

Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Services/LdapConnectionProvider.cs
Fabric.Identity.API/Services/LdapProviderService.cs
Fabric.Identity.API/scripts/setup-samples.sh

Also, catch and log LdapReferralException.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/51)

Allow following referrals when querying LDAP. 

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/52)

Update install script  for ldap settings

---

Fabric.Identity.API/scripts/create-nuspec.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/54)

Added a script to create a nuspec file during build.

---

Fabric.Identity.API/scripts/create-nuspec.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/57)

Updated create-nuspec.sh to remove artifactpath parameter

---

Fabric.Identity.API/scripts/Fabric.Identity.nuspec
Fabric.Identity.API/scripts/Fabric.Identity.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/59)

Added nuspec files for packaging Identity.

---

Fabric.Identity.API/Infrastructure/QueryStringBinding/CommaSeparatedAttribute.cs
Fabric.Identity.API/Infrastructure/QueryStringBinding/CommaSeparatedQueryStringConvention.cs
Fabric.Identity.API/Infrastructure/QueryStringBinding/SeparatedQueryStringAttribute.cs
Fabric.Identity.API/Infrastructure/QueryStringBinding/SeparatedQueryStringValueProvider.cs
Fabric.Identity.API/Infrastructure/QueryStringBinding/SeparatedQueryStringValueProviderFactory.cs
Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.IntegrationTests/UsersStoreTests.cs
Fabric.Identity.UnitTests/SeparatedQueryStringValueProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/60)

allow support for comma separated query string values

---

Fabric.Identity.API/Infrastructure/QueryStringBinding/SeparatedQueryStringAttribute.cs
Fabric.Identity.API/Infrastructure/QueryStringBinding/SeparatedQueryStringValueProvider.cs
Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Management/BaseController.cs
Fabric.Identity.API/Management/ClientController.cs
Fabric.Identity.FunctionalTests/tests/identitytests.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/62)

fixed a bug where client secrets were not being hashed when being reset

---

Fabric.Identity.API/Authorization/BaseAuthorizationHandler.cs
Fabric.Identity.API/Authorization/ReadAuthorizationHandler.cs
Fabric.Identity.API/Authorization/RegistrationAuthorizationHandler.cs
Fabric.Identity.API/Authorization/SearchUserAuthorizationHandler.cs
Fabric.Identity.API/Authorization/SearchUserScopeRequirement.cs
Fabric.Identity.API/Extensions/ServiceCollectionExtensions.cs
Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Management/ClientController.cs
Fabric.Identity.API/Management/IdentityProvidersController.cs
Fabric.Identity.API/Management/IdentityResourceController.cs
Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.IntegrationTests/IntegrationTestsFixture.cs
Fabric.Identity.UnitTests/SearchUsersAuthorizationHandlerTests.cs

also refactored the existing authorization handlers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/63)

added new scope fabric/identity.searchusers

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/setup-samples.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/64)

add search users scope to clients and resources in install scripts

---

Fabric.Identity.API/Configuration/IdentityConfigurationProvider.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/67)

Added support for encrypting the ldap password

---

Fabric.Identity.API/FabricIdentityConstants.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/66)

made constants for authorization policy internal to hopefully please codacy

---

Fabric.Identity.API/Extensions/ServiceCollectionExtensions.cs
Fabric.Identity.API/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/69)

Removed CouchDbEventSink registration from DI container.

---

Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Management/BaseController.cs
Fabric.Identity.API/Management/ClientController.cs
Fabric.Identity.API/Management/IdentityResourceController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/73)

added 409 status code  to swagger docs for post and put

---

Fabric.Identity.API/Exceptions/AlreadyExistsException.cs
Fabric.Identity.API/FabricIdentityEnums.cs
Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Management/BaseController.cs
Fabric.Identity.API/Management/ClientController.cs
Fabric.Identity.API/Management/IdentityResourceController.cs
Fabric.Identity.API/Management/UsersController.cs
Fabric.Identity.API/Services/CouchDbAccessService.cs
Fabric.Identity.API/Services/InMemoryDocumentService.cs
Fabric.Identity.API/Validation/ApiResourceValidator.cs
Fabric.Identity.API/Validation/ClientValidator.cs
Fabric.Identity.API/Validation/IdentityResourceValidator.cs
Fabric.Identity.IntegrationTests/ClientRegistrationTests.cs
Fabric.Identity.IntegrationTests/ResourceStoreTests.cs
Fabric.Identity.IntegrationTests/UsersStoreTests.cs
Fabric.Identity.UnitTests/BaseControllerTests.cs
Fabric.Identity.UnitTests/ClassFixtures/InMemoryUserDocumentFixture.cs
Fabric.Identity.UnitTests/ClientRegistrationTests.cs
Fabric.Identity.UnitTests/IdentityProviderConfigurationServiceTests.cs

when a duplicate is added return a 409
when deleting a non existent resource return 404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/72)

update response status codes 

---

Fabric.Identity.API/Persistence/SqlServer/Entities/ApiResourceEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/ClaimEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/ClientEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/EntityExtensions.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/ISoftDelete.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/ITrackable.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/UserClaimEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/UserEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Entities/UserLoginEntity.cs
Fabric.Identity.API/Persistence/SqlServer/Services/IIdentityDbContext.cs
Fabric.Identity.API/Persistence/SqlServer/Services/IdentityDbContext.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerApiResourceStore.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerClientStore.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerIdentityResourceStore.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerUserStore.cs

i started on the user data model. 
framed in the user store but not fully implemented. 
finished up rename of domain model classes to be entity classes which is the real reason to check this in now, so that brian can help with the persisted grant store and not have a nasty merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/86)

the branch name is misleading as this branch is mostly about the user model 

---

Fabric.Identity.IntegrationTests/ControllerTests/CouchDb/CouchDbApiResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/CouchDb/CouchDbClientRegistrationTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/CouchDb/CouchDbIdentityProvidersControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/CouchDb/CouchDbIdentityResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/CouchDb/CouchDbUsersControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ApiResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ClientRegistrationTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/IdentityProvidersControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/IdentityResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/UsersControllerTests.cs
Fabric.Identity.IntegrationTests/IntegrationTestsFixture.cs
Fabric.Identity.IntegrationTests/ServiceTests/LdapProviderServiceTests.cs
Fabric.Identity.IntegrationTests/ServiceTests/LdapTestHelper.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/92)

Reorganized namespaces in integration test project.

---

Fabric.Identity.FunctionalTests/tests/identitytests.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/101)

Updated phantomjs settings to allow it to use tls for ssl.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/102)

added support for providing a list of certs for the user to select from during install

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/105)

prompt user for app insights instrumentation key

---

Fabric.Identity.API/Fabric.Identity.API.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/107)

Ignore xml comment warnings on build.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

should we handle the situation where a different version is already installed?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/104)

added code to install the .net core windows server hosting bundle if not found

---

Fabric.Identity.API/scripts/Fabric.Identity.InstallPackage.nuspec

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/108)

fixed SqlServerIncludingTables file name specified in nuspec file

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/109)

add sql server connection string to install config and prompt user to enter 

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/110)

Remove CouchDB and LDAP related settings and checks.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/114)

Fixed a bug when only one site existed in IIS.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/113)

added code to unlock anonymous and windows auth config sections

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

also added expanding environment variables in the selected sites physical path 
added back loading the Web.Administration dll to use the ServerManager when unlocking config sections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/116)

validate connection string by querying sql server

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/117)

added parameter to toggle overwrite of web.config

---

Fabric.Identity.API/scripts/Fabric.Identity.InstallPackage.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/115)

fixed SqlServerIncludingTables publish file name

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

for things that are successful write-host is switched to Write-Success 
for things that are information write-host is switched to Write-Console 
updated a few Write-Host calls to be Write-Error when they are error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/118)

switched write host to use utility wrapper functions

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

Simplified the installation experience a little.
Accept an app pool user from user input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/119)

Add the app pool user to the Identity database

---

Fabric.Identity.SqlServer/Security/IdentityServiceRole.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/122)

grant delete on UserClaims to IdentityServiceRole

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/124)

add read permission for the app pool user on signing key 

---

Fabric.Identity.API/Quickstart/Home/HomeController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/126)

Don't require HTTPS for discovery document.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/127)

Validate the metadata database connection.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/128)

add message confirming app pool user credentials are vaild

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/129)

write out the exception messages to console

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

still trying to figure out how to use QUOTENAME so we can wrap the variables in the user creation script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/132)

use parameters for variables in the sql queries

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/install.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/133)

Force user to enter a service account and remember it.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/136)

always register with discovery service even if fabric registration is already done

---

Fabric.Identity.PerformanceTests/Fabric.Identity.Perf.jmx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/138)

Added threads to increase performance test load.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/139)

Cleaned up script output.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

putting these things closer to the cert selection will let the user know sooner if the cert they selected is bad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/140)

adjust when we ask for app pool user and pk read permission of signing cert

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/141)

ensure script directory is set if exception occurs while directory is changed 

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/143)

ensure cert selection is in the valid range

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/144)

move registration of identity with discovery closer to the discovery url step

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/145)

convert user entered cert selection to an int before comparing against the cert count

---

Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerPersistedGrantStore.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/146)

Change SqlServerPersistedGrantStore to hard delete PersistedGrants.

---

Fabric.Identity.API/Models/ModelExtensions.cs
Fabric.Identity.API/Models/User.cs
Fabric.Identity.API/Models/UserLogin.cs
Fabric.Identity.API/Persistence/SqlServer/Mappers/UserMapper.cs
Fabric.Identity.API/Persistence/SqlServer/Mappers/UserMapperProfile.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerUserStore.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/UserLoginManagerTests.cs
Fabric.Identity.UnitTests/UserLoginManagerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/147)

dont use automapper for the User entity nav collections. map them to entities manually

---

Fabric.Identity.API/Configuration/AppConfiguration.cs
Fabric.Identity.API/Configuration/IAppConfiguration.cs
Fabric.Identity.API/Persistence/SqlServer/EntityModels/UserClaim.cs
Fabric.Identity.API/Persistence/SqlServer/Mappers/UserMapper.cs
Fabric.Identity.API/Persistence/SqlServer/Mappers/UserMapperProfile.cs
Fabric.Identity.API/Persistence/SqlServer/Services/IdentityDbContext.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerUserStore.cs
Fabric.Identity.API/Services/IdentityProviderConfigurationService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.API/Views/Account/Login.cshtml
Fabric.Identity.API/appsettings.json
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/UserLoginManagerTests.cs
Fabric.Identity.SqlServer/Tables/UserClaims.sql
Fabric.Identity.UnitTests/IdentityProviderConfigurationServiceTests.cs

Fix up swagger URL when not running from the top level website.
Add config to disable Windows Auth when running in IIS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/153)

Ensure claims from 3rd party ID provider are pulled through.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/159)

Default to https for installation.

---

Fabric.Identity.API/Configuration/AppConfiguration.cs
Fabric.Identity.API/Configuration/IAppConfiguration.cs
Fabric.Identity.API/Configuration/IdentityProviderSearchSettings.cs
Fabric.Identity.API/Fabric.Identity.API.csproj
Fabric.Identity.API/Infrastructure/PolicyProvider.cs
Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Services/IExternalIdentityProviderService.cs
Fabric.Identity.API/Services/IdPSearchServiceProvider.cs
Fabric.Identity.API/Services/LdapProviderService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.API/appsettings.json
Fabric.Identity.IntegrationTests/IntegrationTestsFixture.cs
Fabric.Identity.IntegrationTests/ServiceTests/LdapProviderServiceTests.cs

added circuit breaker and flag to disable calling idp search
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/160)

call the identity provider search service to get the user first and last name

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.API/scripts/setup-samples.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/161)

register identity search service as an api resource and identity as a client

---

Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Validation/ApiResourceValidator.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ApiResourceControllerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/166)

Fixed a bug in PUT /apiresource.

---

Fabric.Identity.SqlServer/Storage/HCFabricIdentityLogFile1.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/169)

fixed script issue with changing log file mount point name

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/170)

Add the ability to write secrets to web.config.

---

Fabric.Identity.API/Authorization/BaseAuthorizationHandler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/176)

made issuer comparison case insensitive.

---

Fabric.Identity.API/appsettings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/177)

Removed default IssuerUri setting.

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/180)

fixed path concatenation in windows install script

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/181)

Expand environment variables for path of application.

---

Fabric.Identity.API/scripts/Register.ps1

web.config encryption for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/182)

 Don't encrypt secrets when writing to config. We'll leverage built in

---

Fabric.Identity.API/Models/DiscoveryServiceApiModel.cs
Fabric.Identity.API/Models/DiscoveryServiceResponseModel.cs
Fabric.Identity.API/Services/DiscoveryServiceClient.cs
Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Fabric.Identity.UnitTests/Services/DiscoveryServiceClientTests.cs

Update DiscoveryServiceClient to get servives via OData endpoint
Update install script:
- to remove idpsearch registration. 
- Fix up discovery url
- save secrets to config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/184)

Update DiscoveryServiceClient, update install script

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/186)

added role displayName and description to registration script

---

Fabric.Identity.SqlServer/Fabric.Identity.SqlServer.sqlproj
Fabric.Identity.SqlServer/Storage/HCFabricIdentityIndex1.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/187)

updated page verify to checksum and fixed index file extension

---

Fabric.Identity.API/Documentation/build.gradle
Fabric.Identity.API/Fabric.Identity.API.csproj
Fabric.Identity.API/Startup.cs

This setup works for relative paths so we can install in a sub application of the main iis site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/190)

Update swagger URL.

---

Fabric.Identity.API/Persistence/SqlServer/EntityModels/ApiScope.cs
Fabric.Identity.API/Persistence/SqlServer/Services/IdentityDbContext.cs
Fabric.Identity.API/Persistence/SqlServer/Stores/SqlServerApiResourceStore.cs
Fabric.Identity.API/scripts/queue-build.sh
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ApiResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ClientRegistrationTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/IdentityResourceControllerTests.cs
Fabric.Identity.SqlServer/Tables/ApiResources.sql
Fabric.Identity.SqlServer/Tables/ApiScopes.sql
Fabric.Identity.SqlServer/Tables/Clients.sql
Fabric.Identity.SqlServer/Tables/IdentityResources.sql

So we can delete and add entities w/ the same name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/198)

Add filters to unique indexes

---

Fabric.Identity.API/Quickstart/Account/AccountController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/200)

Fixed an issue when creating GivenName and FamilyName claims.

---

Fabric.Identity.API/Extensions/ServiceCollectionExtensions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/205)

Fixed a DI registration so we are using a transient profile service.

---

Fabric.Identity.API/Management/ApiResourceController.cs
Fabric.Identity.API/Management/ClientController.cs
Fabric.Identity.FunctionalTests/tests/identitytests.js
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ApiResourceControllerTests.cs
Fabric.Identity.IntegrationTests/ControllerTests/InMemory/ClientRegistrationTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/207)

Updated the resetPassword endpoints from GET to POST.

---

Fabric.Identity.API/Fabric.Identity.API.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/208)

Add version info to csproj.

---

CODEOWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/210)

Add code owners file.

---

Fabric.Identity.API/scripts/Register.ps1

This allows clients like SAMD which are not placed in the discovery service to bypass the discovery service request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/211)

Allow registration of hybrid/Pkce clients not in Discovery Service

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

Backport api/client secret reset into 18.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/213)

Backport secret reset to 18.1

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

Remove Add-DiscoveryRegistration (moved into Install utilities)
Register discovery step moved after publish step
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/215)

Register identity with discovery

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

Updating 18.1
Move registration step to fabric utils, identity passes version to register function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/216)

Move DiscoveryRegistration to fabric utils

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

Move registration step after app install so app.dll exists to get version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/218)

Move discovery registration after app install

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/220)

Set discovery version during registration, if not exists

---

Fabric.Identity.API/scripts/identity-cli.psm1
Fabric.Identity.API/scripts/tests/identity-cli.tests.ps1

Also renamed the Create- functions to New-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/224)

Initial Get-ClientRegistration, unit test place holders

---

Fabric.Identity.API/scripts/tests/CatalystDosIdentity.functional.tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/231)

Rename module so functional tests run

---

Fabric.Identity.FunctionalTests/tests/identitytests.js

just a quick change to allow the test time to pass with service spin up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/232)

Update max timeout to make test more stable

---

Fabric.Identity.API/scripts/CatalystDosIdentity.psm1
Fabric.Identity.API/scripts/tests/CatalystDosIdentity.tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/233)

merge additions for identity cli api management

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/237)

Write appInsightsKey to common section

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/238)

Update installer on upgrade

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/239)

Installer client now updates on upgrades

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/240)

Update Register.ps1 to associate a role to a group based on config.

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/247)

added quiet flag to registration script

---

Fabric.Identity.API/scripts/Install-Identity-Windows.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/246)

add scope to installer registration

---

Fabric.Identity.API/scripts/Register.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/248)

allow register.ps1 to pass in registration file

---

Fabric.Identity.API/scripts/Install-Identity.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/249)

Fixed default parameter value.

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/253)

Fixed allowed scopes for install registration client.

---

Fabric.Identity.API/Configuration/IdentityConfigurationProvider.cs
Fabric.Identity.IntegrationTests/ServiceTests/IdentityConfigurationProviderTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/261)

Add decryption for azure client secret.

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/260)

Azure settings only written when $useAzure -eq $true

---

Fabric.Identity.API/Exceptions/InvalidIssuerException.cs
Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Models/AzureActiveDirectoryJwtClaimTypes.cs
Fabric.Identity.API/Models/ClaimsResult.cs
Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Services/ClaimsService.cs
Fabric.Identity.API/Services/IClaimsService.cs
Fabric.Identity.API/Startup.cs
Fabric.Identity.UnitTests/Helpers/TestHelper.cs
Fabric.Identity.UnitTests/Services/ClaimsServiceTests.cs

Add Azure AD OID as Subject Id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/259)

Add Azure AD OID as Subject Id

---

Fabric.Identity.API/FabricIdentityConstants.cs
Fabric.Identity.API/Services/ClaimsService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/268)

Update Authentication Scheme Name for AzureAD

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

Change message to print app pool name instead of app pool object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/269)

Change Write-DosMessage level to fatal instead of error

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/270)

Change Register-Identity replyUrls to a string array

---

Fabric.Identity.API/scripts/Install-Identity.ps1

Move azure related settings below the prompt for DiscoveryService
Use the discoveryServiceUrl variable instead of trying to read from the installconfig twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/272)

Move azure related settings below the prompt for DiscoveryService

---

Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Quickstart/Account/LoginViewModel.cs
Fabric.Identity.API/Views/Account/Login.cshtml

Task: https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/156377

I added a check for cookies to the login endpoint.

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

version change

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/Install-Identity.ps1

Ticket URL: https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/162645

I added saving the identity URL to EDWAdmin to the install script.

---

Fabric.Identity.API/scripts/Install-Identity.ps1

Removed client secret from writing to the logs and replaced with generic client secret has been created.

Removed client secret from writing to the logs.

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1

Allow multi tenant registration

Allow multi tenant registration

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

Move tenant alias settings into identity/idpss web.configs

Move tenant alias settings into identity/idpss web.configs

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/Install-Identity.ps1
Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1

updates because of noDiscovery switch and reorganized idpss to flow like identity. found an identity scope variable not populated that was located in common .

updates to identity, identity.utilities and idpss scripts

---

Fabric.Identity.API/Quickstart/Account/AccountController.cs
Fabric.Identity.API/Views/Account/Login.cshtml

Bug link:
https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/167947

Fixed the test cookie expiration blocking users from logging in.

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

Changed the script from getting the logged in users domain to now getting the machine domain that is being used.

Changed from getting user domain to machine domain

---

Fabric.Identity.API/Views/Account/Login.cshtml

Removed the links at the footer of the Identity login since they pointed nowhere.

Removed Links in Identity Login

---

Fabric.Identity.API/scripts/install.config

Add application endpoint to default install.config

Add applicationEndpoint to install.config

---

Fabric.Identity.API/scripts/Install-Discovery.ps1
Fabric.Identity.API/scripts/Install-Identity-Discovery-IdPSS.ps1
Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/Install-Identity.ps1
Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1
Fabric.Identity.API/scripts/install.config
Fabric.Identity.API/scripts/tests/Install-Identity-Utilities.tests.ps1

right now, everything is installed altogether.  Perhaps I should remove IDPSS and Discovery, then add them to a script separately from identity.  That script would call all 3

Moved discovery service installation script into the identity script.

---

Fabric.Identity.API/Startup.cs
Fabric.Identity.API/Views/Shared/UnauthorizedError.cshtml
Fabric.Identity.API/scripts/Install-Discovery.ps1
Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1
Fabric.Identity.API/scripts/Install-Identity-Discovery-IdPSS.ps1
Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/Install-Identity.ps1
Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1
Fabric.Identity.API/scripts/install.config
Fabric.Identity.API/scripts/tests/Install-IdPSS-Utilities.tests.ps1
Fabric.Identity.API/scripts/tests/Install-Identity-Utilities.tests.ps1

Added a default 401 error page for Identity.

Added Default 401

---

Fabric.Identity.API/scripts/Install-Identity-Discovery-IdPSS.ps1

This error looks like it generated some wacky stuff.  This will resolve the issues.

missing passing config store

---

Fabric.Identity.API/scripts/install.config

applicationEndpoint -> applicationEndPoint

Change applicationEndPoint casing

---

Fabric.Identity.API/scripts/Install-Discovery.ps1
Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

this code adds a default webServerDomain that prevents powershell script failure

add webserverdomain code

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1
Fabric.Identity.API/scripts/Register-Identity-IdPSS.ps1

added azuresettings.config to the copy scripts section in the Fabric.Identity build, so it is included in Fabric.Identity.InstallPackage

add minor script changes to include azuresettings.config file.

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

Migrated from fabric-install-utilities
Added parameter for manual secret entry if needed

Migrate installer secret reset function

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1

issue with parameter name

---

Fabric.Identity.API/scripts/Install-Identity.ps1

Update variable for install

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/tests/Get-IdentityEncryptionCertificate.tests.ps1

(Fresh install/clean install.config case)

Issue with install when no thumbprint is in install.config

---

Fabric.Identity.API/Configuration/ExternalIdProviderSettings.cs
Fabric.Identity.API/Extensions/ApplicationBuilderExtensions.cs
Fabric.Identity.API/appsettings.json
Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1
Fabric.Identity.IntegrationTests/appsettings.json

latest changes for oidc to work for the most part

Changes to get OIDC to work

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

latest DIU

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

update DIU 1.5

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

update DIU 1.x should be 1.6

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1

Clean up identity install artifact
Views folder is causing issues with identity after upgrading to .net core 2.2

Clean up identity install artifacts

---

Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Fabric.Identity.API/scripts/setup-samples.sh

add identity.searchusers scope

add identity.searchusers scope

---

Fabric.Identity.API/scripts/Install-Identity-Discovery-IdPSS.ps1

Updated installer script to pull latest version of DIU.  Lines 5-15 are actually new codes. The rest of the changes or formatting changes caused by VSCode.

Enforced latest version of DIU in Installer script

---

Fabric.Identity.API/Configuration/IdentityConfigurationProvider.cs
Fabric.Identity.IntegrationTests/ServiceTests/IdentityConfigurationProviderTests.cs

Add decryption of AzureActiveDirectoryClientSettings's secret

Add decryption of azure secrets

---

Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1
Fabric.Identity.API/scripts/Register-Identity-IdPSS.ps1

Handle null tenants list when single registration

Update bad variable in Register-Identity

---

Fabric.Identity.API/Startup.cs

- Updating Startup to set cookie attributes when identity server cookies are appended and deleted
- Added a check to see if the protocol is HTTPS, so the functional tests won't break, since they run using HTTP. Since the secure attribute is being set, the cookies won't be sent back to apps over HTTP

Cookie policy Update
