HealthCatalyst/Fabric.Identity

- Fabric.Identity.API/Authorization/IHaveAuthorizationClaimType.cs
- Fabric.Identity.API/Authorization/ReadAuthorizationHandler.cs
- Fabric.Identity.API/Authorization/ReadScopeRequirement.cs
- Fabric.Identity.API/Authorization/RegisteredClientThresholdRequirement.cs
- Fabric.Identity.API/Documentation/SecurityRequirementsOperationFilter.cs
currently on the users api uses the fabric read scope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/37)
> show the oauth scope for the api's that use fabric read scope

- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
- Fabric.Identity.API/scripts/install.config
This will allow us to simply edit the config parameters in a file, and call the installation script without passing parameters. We also allow pushing a new variable to the config (with an option to encrypt) so it can be used downstream.
This pull request also encompasses moving prerequisite tests and registration steps to the identity install script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/38)
> Updated installation script to move parameters to configuration.

- Fabric.Identity.API/Configuration/AppConfiguration.cs
- Fabric.Identity.API/Configuration/IAppConfiguration.cs
- Fabric.Identity.API/Configuration/LdapSettings.cs
- Fabric.Identity.API/Fabric.Identity.API.csproj
- Fabric.Identity.API/Models/ExternalUser.cs
- Fabric.Identity.API/Quickstart/Account/AccountController.cs
- Fabric.Identity.API/Services/IExternalIdentityProviderService.cs
- Fabric.Identity.API/Services/ILdapConnectionProvider.cs
- Fabric.Identity.API/Services/LdapConnectionProvider.cs
- Fabric.Identity.API/Services/LdapProviderService.cs
- Fabric.Identity.API/Startup.cs
- Fabric.Identity.API/appsettings.json
- Fabric.Identity.API/scripts/set-environment-couchdb.sh
- Fabric.Identity.IntegrationTests/LdapProviderServiceTests.cs
- Fabric.Identity.IntegrationTests/appsettings.json
I've added the ability to get the user's first name, middle name and last name from Active Directory. Integration tests have also been added, but require that you have an installation of open ldap on your machine. I have built a docker image for that and will be creating a repo to contain that code shortly.
I tried to make the code degrade gracefully if no ldap settings are specified. However, if ldap settings are specified and we can't connect to ldap, we will throw an exception so we are 'failing fast' in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/46)
> Implement user search in Ldap

- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
- Fabric.Identity.API/web.config
I added logic to:
1 - Make sure that we verify the existence of the zipPackage before proceeding with the script.
2 - Make sure that we verify that the cert thumbprints before proceeding with the script.
3 - Clean up non printable characters from the thumbprint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/53)
> Install script improvements

- Fabric.Identity.API/Configuration/IdentityConfigurationProvider.cs
- Fabric.Identity.API/Configuration/SigningCertificateSettings.cs
- Fabric.Identity.API/Extensions/IdentityServerBuilderExtensions.cs
- Fabric.Identity.API/Services/ICertificateService.cs
- Fabric.Identity.API/Services/LinuxCertificateService.cs
- Fabric.Identity.API/Services/WindowsCertificateService.cs
- Fabric.Identity.API/appsettings.json
- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
- Fabric.Identity.API/scripts/install.config
- Fabric.Identity.UnitTests/LinuxCertificateServiceTests.cs
- Fabric.Identity.UnitTests/UserLoginManagerTests.cs
- Fabric.Identity.UnitTests/WindowsCertificateServiceTests.cs
Allow defining both an encryption and signing certificate so that the signing certificate can be rotated without breaking the encryption of configuration items in the web.config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/55)
> Split Encryption and Signing cert

- Fabric.Identity.API/scripts/Fabric.Identity.InstallPackage.nuspec
- Fabric.Identity.API/scripts/Fabric.Identity.InstallPackage.targets
Updated nuspec and targets so zip file gets copied on build of the installer properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/61)
> Updated nuspec and targets

- Fabric.Identity.API/CouchDb/CouchDbBootstrapper.cs
- Fabric.Identity.API/CouchDb/DocumentDbBootstrapper.cs
While we have an administrator user for the overall CouchDb instance, if we don't have a user defined in the individual database, the database itself is public and authentication is not required to make updates to the data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/70)
> Add a user in CouchDbBootstrapper.

- Fabric.Identity.API/scripts/Install-Identity-Dev.ps1
I added a script that will install Fabric.Identity on a dev machine in IIS and set everything up to do windows authentication. This will help other teams test and debug locally with windows auth turned on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/74)
> Added a script to install Fabric.Identity in IIS on a developer machine.

- Fabric.Identity.API/scripts/run-all-tests.sh
- Fabric.Identity.API/scripts/run-functional-tests.sh
- Fabric.Identity.API/scripts/run-integration-tests.sh
- Fabric.Identity.API/scripts/run-unit-tests.sh
These scripts are designed to be run from the scripts directory. They basically mimic what the CI build and release pipeline do. 
You can run each script individually, or run the run-all-tests.sh script to run unit, integration and functional tests in one shot.
All the scripts except for the run-unit-tests.sh script take two parameters, one for the couchdb username and one for the couchdb password.
You'll need to have docker running, as we spin up couchdb and openldap for the integration tests as a container. For the functional tests we run couchdb, authorization and identity as containers. We build the identity container from the code in your dev environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> added some basic scripts to run tests more easily.

- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
This will pull the server hosting bundle that has the 1.0.5 and 1.1.2 runtimes. 
Runtimes are not to be confused with SDK - we use the 1.0.4 SDK to build and target the 1.1.2 runtime. This originally confused me, which is why we were pulling the hosting bundle with the 1.0.4 and 1.1.1 runtimes. This would have resulted in having to install the 1.1.2 runtime manually, or getting a 502.5 error on application start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/137)
> Updated the Windows Server Hosting bundle version number

- Fabric.Identity.API/web.config
We originally made this a config setting for when running behind an nginx proxy. In that scenario, identity was calculating the wrong uri, behind IIS, it calculates the correct uri, so for IIS deployments set the config to an empty string so that Identity can set the IssuerUri internally, which is more secure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/171)
> Set IssuerUri config to empty so Identity sets it based on the request.

- Fabric.Identity.API/Configuration/IdentityConfigurationProvider.cs
- Fabric.Identity.API/Extensions/UtilityExtensions.cs
- Fabric.Identity.API/Services/DiscoveryServiceClient.cs
- Fabric.Identity.API/Services/IdPSearchServiceProvider.cs
Ensure the authority URL has a trailing slash before using it to create the token url.
Add additional logging so we have better insight into calls to idpsearch.
Add decryption for the client secret.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/188)
> Minor fixes to issues found during installation

- Fabric.Identity.API/Services/IdPSearchServiceProvider.cs
the call to ensure trailing slash was building a url that looked like:
http://localhost:5009/v1/principals/user?subjectid=/DOMAIN\user
instead of:
http://localhost:5009/v1/principals/user?subjectid=DOMAIN\user
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/197)
> Fixed search service url.

- Fabric.Identity.API/scripts/Register.ps1
1. Allow registering multiple hostnames for implicit clients
2. Providing a better error message when a service is not registered
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/203)
> Updated Register.ps1 script to:

- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
Trim ending slash after prompting user input for discovery url so either user input or already existing discovery url has it's ending slash removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/221)
> Trim ending discovery slash

- Fabric.Identity.API/scripts/Install-Identity-Windows.ps1
- Fabric.Identity.API/scripts/Register.ps1
I got an error upgrading, but not the same error, I got it in the DiscoveryServiceClient, so I added code to add /v1 to the default discovery service url, if not present from having a previous installation. 
I still added more error code to where his error was thrown in the Fabric.Registration, but I think the natural progression would be to upgrade first Fabric.Identity, then Fabric.Authorization, then Fabric.Registration, and this code addition will work. If they were to skip over Fabric.Identity, then the /v1 code addition would need to be duplicated in the others.  I haven't been able to test the error code addition, since I didn't get the same error as him. May need to over the shoulder with him, through his process before I check in.
---
This change is [<img …
> added upgrade change to append a /v1 to discoveryservice url if not present

- Fabric.Identity.API/Quickstart/Account/AccountController.cs
- Fabric.Identity.API/Services/ClaimsService.cs
- Fabric.Identity.API/Services/IClaimsService.cs
- Fabric.Identity.UnitTests/Services/ClaimsServiceTests.cs
UserId needed to be subject id for Azure AD
Moved around some private functions to keep all public functions together.
Added new function "GetEffectiveUserId".  Based on conversation with @michaelvidal24 , The user Id that is used to store a user in the database was being set to values for AD, even though the user was logging into Identity with an Azure AD account.  This will select the subject ID if it is from Azure AD, else it will use the user Id claim that was pulled in the "GetUserIdClaim" step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/healthcatalyst/fabric.identity/265)
> UserId needed to be subject id for Azure AD

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Moving thumbprint to the first of the output after getting feedback from Command Center that sometimes the name is a match and the thumbprint gets cut off in our formatted table.
> Move thumbprint so its always visible

- Fabric.Identity.API/scripts/Register-Identity-IdPSS.ps1
Check to see if user supplied either registerIdentity and/or registerIdPSS switch with this script. If not, display a message with examples to use.
> Add check to see if any switches were applied

- Fabric.Identity.API/Fabric.Identity.API.csproj
- Fabric.Identity.API/Services/LinuxCertificateService.cs
Removed an unused nuget that was pulling in another nuget that was causing build warnings.
> Remove unused nuget package.

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
- Fabric.Identity.API/scripts/Install-Identity.ps1
- Fabric.Identity.API/scripts/tests/Install-Identity-Utilities.tests.ps1
Using the newly introduced "Get-WebRequestDownload" function in DosInstallUtilities to remove the progress bar when downloading assets for installation.
> Remove progress bar when downloading assets during installation

- Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1
Bug link:
https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/168485
> I fixed the name being used to filter Azure settings for IdPSS.

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
This fixes the issue where we could not create a registration body, and as a bonus since we import CataystDosIdentity after Fabric-Install-Utilities, we can use the CatalystDosIdentity version of Get-AccessToken.
> Install and Import CatalystDosIdentity

- Fabric.Identity.API/Quickstart/Account/AccountController.cs
Otherwise we occasionally show the message that we can't set a cookie incorrectly.
> Don't remove test cookie until we are able to sign the user in.

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
- Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1
DosInstallUtitlities uses the AppName parameter to display an information message for the service getting deployed.
> DosInstallUtilities uses the AppName parameter, remove unused credential

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Refactored how the parameters for theGet-TenantSettingsFromInstallConfig variable were being passed.  Current version was throwing error and preventing correct install path from being passed.
> tweaked parameters for Get-TenantSettingsFromInstallConfig

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Changed to get the Forest Name of the domain in case we change our naming convention down the road.
> Changed how to get machine domain

- Fabric.Identity.API/scripts/install.config
We seem to rely on the identity logs instead of the DosInstall logs. Just added the necessary variables to allow DosInstall logs to work also.
> updating to actually set-logging configuration for identity

- Fabric.Identity.API/scripts/Install-IdPSS-Utilities.psm1
- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
Do not require PSCredentials (let the azureAD module handle that)
> Use a filter to find graph api permissions

- Fabric.Identity.API/scripts/Install-Discovery.ps1
- Fabric.Identity.API/scripts/Install-Identity.ps1
- Fabric.Identity.API/scripts/Install-IdentityProviderSearchService.ps1
Weird bug.  If you call this individually, then it validates the hashtable.
If you call it from the main script, it works with no validation.
> removed validation from install-discovery script

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
The cert selection output is only displaying non-expired certs
Once a cert is 'selected', then code would pull from all certs including expired ones, so if any expired certs exists, then the selection would be offset.
> Only select from list of valid displayed certs

- Fabric.Identity.API/Models/ModelExtensions.cs
The scope can be null I guess , since the linq statement may still find what it needs.
> generic unhelpful error

- Fabric.Identity.API/scripts/Install-Identity-Utilities.psm1
* Update Install-Identity-Utilities.New-IdentityEncryptionCerfificat() to check the OS version and call the correct version of New-SelfSignedCertificate, since the method signatures are different for Windows Server 2012 and 2016.
* All parameter values included in the 2016 version call seem to be default on the 2012 call, with the friendly name as an exception. This is set after the cert is created
*DnsName creates the subject in the 2012 version
> Update Identity Install Utilities to check OS version for cert creation

- Fabric.Identity.API/Quickstart/Account/AccountController.cs
This fixes an issue with Access Control login showing an error from Identity when UseDiscovery for Identity is enabled: https://dev.azure.com/healthcatalyst/CAP/_workitems/edit/196332
Replaced IExternalIdentityProviderService used during AccountController.ExternalLogin with IPrincipalSearchService.  Registered IExternalIdentityProviderService class IdPSearchServiceProvider uses idPSS which may not be installed.  Switching to IPrincipalSearchService (registered with PrincipalSearchService) uses code already inside Identity and moved from idPSS to try to search for the user.
> Change identity provider service used in AccountController away from idPSS

- Fabric.Identity.API/Startup.cs
Adding a cookie policy to update to default cookies that IdentityServer4 creates behind the scenes in middleware. Setting SameSite=None and Secure attribute to fix cross site errors with OpenId with future chrome update. See work item 194264 in Azure DevOps for more details about the issues with chrome 80.
> Adding a cookie policy to update to default cookie attributes for Identity
